version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - 3000:3000
    depends_on:
      - solr

  solr:
    build: ./src
    container_name: solr
    ports:
      - 8983:8983
    volumes: 
      - ./src/data/:/data/
      - ./src/solr_config/:/solr_config/