version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src
      - /app/node_modules
    stdin_open: true
    tty: true


#  backend:
#    build: ./backend
#    ports:
#      - 3001:3001
#    volumes:
#      - ./backend:/data
